const TMDB_BASE='https://api.themoviedb.org/3';
const IMAGE_BASE='https://image.tmdb.org/t/p/';
const CACHE_MS=Number(process.env.TMDB_CACHE_MS||60*60*1000);
const cache=new Map();
function key(){return String(process.env.TMDB_API_KEY||'').trim()}
export function tmdbConfigured(){return Boolean(key())}
async function tmdbFetch(path,params={}){const token=key();if(!token){const e=new Error('TMDB_API_KEY is not configured on the server.');e.status=503;throw e}const url=new URL(TMDB_BASE+path);Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')url.searchParams.set(k,String(v))});const headers={Accept:'application/json'};if(token.startsWith('eyJ'))headers.Authorization=`Bearer ${token}`;else url.searchParams.set('api_key',token);const r=await fetch(url,{headers});const body=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(body?.status_message||`TMDB API returned ${r.status}`);e.status=r.status;e.tmdb=body;throw e}return body}
async function cached(k,loader){const hit=cache.get(k);if(hit&&hit.expires>Date.now())return {...hit.data,cached:true};const data=await loader();cache.set(k,{data,expires:Date.now()+CACHE_MS});return {...data,cached:false}}
function normalize(m){return {...m,poster_url:m.poster_path?IMAGE_BASE+'w500'+m.poster_path:null,backdrop_url:m.backdrop_path?IMAGE_BASE+'w1280'+m.backdrop_path:null,year:m.release_date?m.release_date.slice(0,4):null,source:'TMDB'}}
export async function tmdbSearch(q,page=1){const query=String(q||'').trim();if(!query)return{results:[],total_results:0};return cached(`search:${query.toLowerCase()}:${page}`,async()=>{const d=await tmdbFetch('/search/movie',{query,page,include_adult:false});return{results:(d.results||[]).map(normalize),page:d.page,total_pages:d.total_pages,total_results:d.total_results}})}
export async function tmdbPopular(page=1,sort='popularity.desc'){return cached(`discover:${page}:${sort}`,async()=>{const d=await tmdbFetch('/discover/movie',{page,sort_by:sort,include_adult:false});return{results:(d.results||[]).map(normalize),page:d.page,total_pages:d.total_pages,total_results:d.total_results}})}
export async function tmdbDetails(id){return cached(`detail:${id}`,async()=>{const d=await tmdbFetch(`/movie/${encodeURIComponent(id)}`,{append_to_response:'credits,videos'});return{...normalize(d),poster_url:d.poster_path?IMAGE_BASE+'w500'+d.poster_path:null,poster_large:d.poster_path?IMAGE_BASE+'original'+d.poster_path:null,backdrop_url:d.backdrop_path?IMAGE_BASE+'w1280'+d.backdrop_path:null,cast:(d.credits?.cast||[]).slice(0,12).map(c=>({id:c.id,name:c.name,character:c.character,headshot_url:c.profile_path?IMAGE_BASE+'w185'+c.profile_path:null})),trailer:(d.videos?.results||[]).find(v=>v.site==='YouTube'&&(v.type==='Trailer'||v.type==='Teaser'))?.key||null}})}
export async function tmdbPerson(id){return cached(`person:${id}`,async()=>{const d=await tmdbFetch(`/person/${encodeURIComponent(id)}`,{append_to_response:'combined_credits'});const credits=(d.combined_credits?.cast||[]).filter(x=>x.media_type==='movie').sort((a,b)=>(b.popularity||0)-(a.popularity||0)).slice(0,30);return{id:d.id,name:d.name,biography:d.biography||'',birthday:d.birthday||null,deathday:d.deathday||null,place_of_birth:d.place_of_birth||null,known_for_department:d.known_for_department||null,profile_url:d.profile_path?IMAGE_BASE+'original'+d.profile_path:null,credits:credits.map(x=>({id:x.id,title:x.title,release_date:x.release_date||null,character:x.character||'',poster_url:x.poster_path?IMAGE_BASE+'w500'+x.poster_path:null}))}})}
export async function tmdbProviders(id,region='NG'){const d=await cached(`providers:${id}:${region}`,()=>tmdbFetch(`/movie/${encodeURIComponent(id)}/watch/providers`));const r=d.results?.[String(region).toUpperCase()]||{};return{region:String(region).toUpperCase(),link:r.link||null,flatrate:r.flatrate||[],free:r.free||[],ads:r.ads||[],rent:r.rent||[],buy:r.buy||[],source:'TMDB / JustWatch'}}
export async function tmdbStatus(){return tmdbFetch('/configuration')}
export function registerTmdbRoutes(app){app.get('/api/tmdb-test',async(_req,res)=>{const started=Date.now();try{await tmdbStatus();res.json({ok:true,tmdb_reachable:true,authenticated:true,elapsed_ms:Date.now()-started,tmdb_api_key_configured:true,message:'TMDB API is reachable and the key is working.'})}catch(e){res.status(e.status||502).json({ok:false,tmdb_reachable:Boolean(e.tmdb),authenticated:false,elapsed_ms:Date.now()-started,tmdb_api_key_configured:tmdbConfigured(),tmdb_error:e.tmdb||{message:e.message}})}});app.get('/api/tmdb-movies',async(req,res)=>{try{const q=String(req.query.q||'').trim(),page=Math.max(Number(req.query.page)||1,1),sort=String(req.query.sort||'popularity.desc');const data=q?await tmdbSearch(q,page):await tmdbPopular(page,sort);res.json({...data,query:q,source:'TMDB'})}catch(e){res.status(e.status||500).json({error:'Unable to fetch TMDB movies.',message:e.message})}});app.get('/api/tmdb-movies/:id',async(req,res)=>{try{res.json(await tmdbDetails(req.params.id))}catch(e){res.status(e.status||500).json({error:'Unable to fetch TMDB movie details.',message:e.message})}});app.get('/api/tmdb-movies/:id/providers',async(req,res)=>{try{res.json(await tmdbProviders(req.params.id,req.query.region||process.env.TMDB_REGION||'NG'))}catch(e){res.status(e.status||500).json({error:'Unable to fetch TMDB providers.',message:e.message})}});app.get('/api/tmdb-people/:id',async(req,res)=>{try{res.json(await tmdbPerson(req.params.id))}catch(e){res.status(e.status||500).json({error:'Unable to fetch TMDB artist details.',message:e.message})}})}